import React, { useState, useRef, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { addChatbotMessage } from '../store/threatSlice';
import { MessageSquare, Send, Terminal, ShieldAlert } from 'lucide-react';
import CyberCard from '../components/CyberCard';
import axios from 'axios';

const SecurityChatbot = () => {
  const dispatch = useDispatch();
  const { chatbotHistory } = useSelector((state) => state.threat);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  
  const bottomRef = useRef(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatbotHistory, isTyping]);

  const quickQuestions = [
    "Summarize today's incidents",
    "Explain what is SQL Injection",
    "How to stop SSH brute force?",
    "Generate incident report"
  ];

  const handleSendMessage = async (messageText) => {
    if (!messageText.trim()) return;

    // Dispatch User Message
    dispatch(addChatbotMessage({ sender: 'user', text: messageText }));
    setInput('');
    setIsTyping(true);

    try {
      const response = await axios.post('/api/metrics/chat', { message: messageText });
      dispatch(addChatbotMessage({ sender: 'bot', text: response.data.response }));
    } catch (err) {
      // Mock Fallback Client Simulation matching backend services/gemini_client.py
      setTimeout(() => {
        const msg = messageText.toLowerCase();
        let reply = '';
        if (msg.includes('sql')) {
          reply = "### SQL Injection (SQLi) Explanation\n\nSQL Injection occurs when malicious SQL payloads are injected into server fields.\n\n**Best Mitigations:**\n1. Use parameterized queries.\n2. Enforce Strict DB access limits.";
        } else if (msg.includes('brute force') || msg.includes('ssh')) {
          reply = "### SSH Brute Force Controls\n\n**Action Items:**\n- Disable password login (use keys instead).\n- Change SSH port to a random high number.\n- Deploy Fail2ban to block offending IP subnets.";
        } else if (msg.includes('summarize') || msg.includes('incident') || msg.includes('alert')) {
          reply = "### Security Incidents Summary\n\nCurrently, there are **2 Active Incidents**:\n- **inc_001 (High)**: SSH Brute force at host Database-Core-01.\n- **inc_002 (Critical)**: Local File Inclusion attempt at Gateway Server.\n\n**Recommendation**: Verify perimeter rules for IP `203.0.113.195` immediately.";
        } else if (msg.includes('report')) {
          reply = "### SOC Incident Executive Report\n\n- **Interval**: Today's active log period.\n- **Alerts Logged**: 4 events analyzed.\n- **Status**: 100% perimeter compliance score.\n\n*Generated by DarkWatch Copilot*";
        } else {
          reply = `I processed your request for *"${messageText}"*.\n\nI can assist you with explaining exploit codes, listing open vulnerability tickets, or summarizing firewall telemetry rules.`;
        }

        dispatch(addChatbotMessage({ sender: 'bot', text: reply }));
        setIsTyping(false);
      }, 700);
    } finally {
      // Done
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-[calc(100vh-7rem)]">
      {/* Quick Queries Panel */}
      <div className="space-y-4">
        <CyberCard title="AI Copilot Command Prompts" icon={ShieldAlert}>
          <div className="space-y-2.5 mt-2">
            {quickQuestions.map((q, idx) => (
              <button 
                key={idx}
                onClick={() => handleSendMessage(q)}
                className="w-full p-3 bg-cyber-secondary/30 border border-white/5 hover:border-cyber-accent/40 rounded-sm text-left font-mono text-[11px] text-slate-300 hover:text-white transition-all hover:translate-x-1"
              >
                &gt; {q}
              </button>
            ))}
          </div>
        </CyberCard>
      </div>

      {/* Main Terminal Chat View */}
      <div className="lg:col-span-2 flex flex-col h-full bg-cyber-cards/75 border border-white/5 rounded-sm p-4 justify-between">
        {/* Terminal Header */}
        <div className="flex items-center gap-2 border-b border-white/5 pb-2 mb-4 font-mono text-xs font-bold text-slate-400">
          <Terminal className="w-4 h-4 text-cyber-accent" />
          <span>DARKWATCH_COPILOT_AI_TERMINAL v1.0.0</span>
        </div>

        {/* Chat History Container */}
        <div className="flex-1 overflow-y-auto space-y-4 pr-2 mb-4 scrollbar-thin">
          {chatbotHistory.map((chat, idx) => (
            <div 
              key={idx} 
              className={`flex flex-col max-w-[85%] font-sans text-xs ${
                chat.sender === 'user' ? 'ml-auto items-end' : 'mr-auto items-start'
              }`}
            >
              <span className="font-mono text-[8px] text-slate-500 uppercase mb-1">
                {chat.sender === 'user' ? 'Operator' : 'DarkWatch Copilot'}
              </span>
              <div 
                className={`p-3 rounded-sm leading-relaxed whitespace-pre-line border font-mono ${
                  chat.sender === 'user' 
                    ? 'bg-cyber-secondary border-cyber-accent/30 text-white' 
                    : 'bg-black/35 border-white/5 text-slate-200'
                }`}
              >
                {chat.text}
              </div>
            </div>
          ))}
          {isTyping && (
            <div className="mr-auto items-start flex flex-col">
              <span className="font-mono text-[8px] text-slate-500 uppercase mb-1">DarkWatch Copilot</span>
              <div className="bg-black/35 border border-white/5 p-3 rounded-sm font-mono text-xs text-cyber-accent animate-pulse">
                &gt; STREAMING AI MODEL TOKEN DECRYPTION...
              </div>
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        {/* User Input Form */}
        <form 
          onSubmit={(e) => {
            e.preventDefault();
            handleSendMessage(input);
          }} 
          className="flex gap-3 border-t border-white/5 pt-4"
        >
          <input 
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask Copilot: 'Explain incident inc_001' or request mitigation guides..."
            className="flex-1 bg-cyber-secondary/50 border border-white/5 rounded-sm px-4 py-2 font-sans text-xs text-slate-100 placeholder-slate-600 focus:outline-none focus:border-cyber-accent focus:shadow-cyber transition-all"
          />
          <button 
            type="submit"
            className="px-4 py-2 bg-cyber-accent hover:opacity-90 rounded-sm text-xs font-sans font-bold uppercase tracking-wider text-white shadow-cyber transition-all flex items-center justify-center gap-1.5"
          >
            <Send className="w-3.5 h-3.5" />
            <span>EXECUTE</span>
          </button>
        </form>
      </div>
    </div>
  );
};

export default SecurityChatbot;
